// Privacy policy. Written to describe what this site actually does, which
// is very little: no analytics, no cookies, no form backend.

import LegalPage from "@/components/shared/LegalPage";
import { siteConfig } from "@/data/site";

export const metadata = {
  title: "Privacy Policy",
  description:
    "How this website handles personal data. In short: it does not collect any.",
};

const sections = [
  {
    heading: "The short version",
    body: [
      "This website does not collect personal data. It runs no analytics, sets no cookies, and has no advertising or tracking scripts of any kind.",
    ],
  },
  {
    heading: "The contact and newsletter forms",
    body: [
      "The enquiry form and the newsletter field do not submit anything to this website. They compose a message in your own email application, which you then choose to send or discard. Nothing you type is stored here, and nothing is transmitted unless you press send in your own email client.",
      "If you do email, that message arrives in an ordinary email inbox and is kept there like any other correspondence. It is not added to a marketing list without your asking, and it is not shared with anyone.",
    ],
  },
  {
    heading: "Hosting and server logs",
    body: [
      "This site is served by a commercial hosting provider. Like nearly all web hosts, it may keep short-lived technical logs, such as IP addresses and browser types, for security and reliability. Those logs are generated by the host, not by this site, and are not used to build any profile of you.",
    ],
  },
  {
    heading: "Fonts and images",
    body: [
      "Typefaces are served from this site's own domain rather than a third party, so loading a page does not report your visit to an external font service. Images are likewise served directly from this site.",
    ],
  },
  {
    heading: "Your rights and questions",
    body: [
      `Since no personal data is collected here, there is generally nothing to access, correct, or delete. If you have emailed and would like that correspondence removed, write to ${siteConfig.email} and it will be deleted.`,
    ],
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      description="What this site does with your data. The honest answer is: nothing."
      updated="July 2026"
      sections={sections}
    />
  );
}
